[package]
name = "p2_procesamiento_por_lotes_multiprogramacion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
termion = "3.0.0"
mki = "0.2.3"
